### ISSUE TITLE
能加个参数替换掉 {{}} 吗

### ISSUE THREAD

**Issue by mimittqq** [fancyboynet/fis3-parser-html-import#1]
angular框架伤不起啊.

因为项目急用 我打算改了原来的传到npm上一个新版本.

**Comment by fancyboynet** [comment]
你是说模板数据渲染可以自定义是吧，类似`{{ data }}`,`$ data $`...

**Comment by mimittqq** [comment]
是啊. 不然angular没法用,,求给个自己配置的空间

**Comment by fancyboynet** [comment]
最新版增加了扩展功能，试试
