### ISSUE TITLE
当不传参数时

### ISSUE THREAD

**Issue by wxzweb** [fancyboynet/fis3-parser-html-import#2]
当不传参数时，angular会报错，如果每个不需要的地方都传参是不是很麻烦了

**Comment by fancyboynet** [comment]
能具体一些吗

**Comment by wxzweb** [comment]
因为设置了所有的html页面都需要经过这个插件编译，当一些引入没有必要传参时，引入的地方会因格式问题报错。
例如
模板：`<div ng-repeat="xx in xxList<%= param %>" ></div>`
引入：`<link rel="import" href="xxx"/>时不加上参数 <%= param %>`将不进行编译，会导致一个报错，angular框架无法识别，是否能在fis3进行编译时 就算没找到data 也去掉此不该出现的模块 谢谢

**Comment by fancyboynet** [comment]
fis-config.js的相关配置可以贴上来吗

**Comment by wxzweb** [comment]
`fis.match('/modules/**.html', {
    parser: fis.plugin('html-import', {
        symbolStart : '<%=',
        symbolEnd : '%>'
    })
});`

**Comment by fancyboynet** [comment]
你的意思是`<link rel="import" href="xxx"/>`没有传`data`字段也要把组件模板`<div ng-repeat="xx in xxList<%= param %>" ></div>`中的`<%= param %>`去掉吗？
既然不需要传数据，组件模板的`<%= param %>`是不是就没有存在的必要呢

**Comment by fancyboynet** [comment]
我好像明白你的意思了，你是说同一个组件，有的地方引入是不需要传这个数据字段的是吗，那可以传空值试试
```
<link rel="import" href="xxx" data="{param:''}"/>
```

**Comment by fancyboynet** [comment]
@wxzweb 调整了一下，不需要传数据时都要传空值确实挺麻烦的，最新版本已经改为`模板自动删除没有匹配的字段`，[试试](https://github.com/fancyboynet/fis3-parser-html-import#基本使用)
